version: "3"
virtualmachines:
- name: idmserver1
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-9-4-05-27-24
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-2  # idm named install fails on 9.3+ an assertion without 2vcpu
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: idmclient1
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-9-4-05-27-24
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-2 # issues with small systems + 9.4
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: ACTIVATION_KEY
