version: "3"
virtualmachines:
- name: host
  image: projects/tmm-instruqt-11-26-2021/global/images/virt-rhel-9-3-11-14-23
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n2-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  nested_virtualization: true
secrets:
- name: ACTIVATION_KEY
- name: SSHKEY
virtualbrowsers:
- name: webconsole
  url: https://host.${_SANDBOX_ID}.instruqt.io:9090