version: "3"
virtualmachines:
- name: rhel1
  image: projects/tmm-instruqt-11-26-2021/global/images/satellite-lab-client1-10-07-24
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: rhel2
  image: projects/tmm-instruqt-11-26-2021/global/images/satellite-lab-client2-10-07-24
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: satellite
  image: projects/tmm-instruqt-11-26-2021/global/images/satellite-server-10-07-24
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: ACTIVATION_KEY
