version: "3"
virtualmachines:
- name: rhel
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-9-3-11-14-23
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-2
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: ACTIVATION_KEY

# DO NOT UPDATE THIS LAB TO NEWER IMAGES. This lab is written to apply specific kernel patch versions. Updating the image, and consequently, the kernel means the lab will break.